spring:
    main:
        # 是否输出banner
        banner-mode: off
    application:
        name: OpenIAM
    # 全局序列化配置
    jackson:
        # ALWAYS         默认策略，任何情况都执行序列化
        # NON_NULL       属性为NULL 不序列化
        # NON_ABSENT     null的不会序列化，但如果类型是AtomicReference，依然会被序列化
        # NON_EMPTY      null、集合数组等没有内容、空字符串等，都不会被序列化
        # NON_DEFAULT    如果字段是默认值，就不会被序列化
        # CUSTOM         此时要指定valueFilter属性，该属性对应一个类，用来自定义判断被JsonInclude修饰的字段是否序列化
        # USE_DEFAULTS   当JsonInclude在类和属性上都有时，优先使用属性上的注解，此时如果在序列化的get方法上使用了JsonInclude，并设置为USE_DEFAULTS，就会使用类注解的设置
        default-property-inclusion: non_empty
        # 设置日期格式
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8


    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: 127.0.0.1
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password: belovedyaoo
        # 连接超时时间（单位：毫秒）
        timeout: 10000
        lettuce:
            pool:
                # 连接池最大连接数
                max-active: 20
                # 连接池最大阻塞等待时间（单位：毫秒）
                max-wait: 10000
                # 连接池中的最大空闲连接
                max-idle: 10
                # 连接池中的最小空闲连接
                min-idle: 0


# MyBatis-Flex
mybatis-flex:
    datasource:
        # 数据数据库
        primary:
            # 数据源类型
            type: com.mysql.cj.jdbc.MysqlDataSource
            # 数据库连接地址
            url: jdbc:mysql://localhost:3307/openiam
            # 数据库用户名 & 密码
            user: root
            password: root
    global-config:
        print-banner: false


server:
    # 应用服务 WEB 访问端口
    port: 8090


# Sa-Token配置
sa-token:
    # 是否输出banner
    is-print: false
    # jwt秘钥
    jwt-secret-key: belovedyaoo
    # token 名称（同时也是 cookie 名称）
    token-name: token
    # token 有效期（单位：秒） 当前设置为 1 天 (86400)，-1 代表永久有效
    timeout: 86400
    # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认 -1 代表不限制，永不冻结
    active-timeout: -1
    # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
    is-concurrent: false
    # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
    # 当前项目使用jwt-simple模式，is-share恒等于false，参考文档 https://sa-token.cc/doc.html#/plugin/jwt-extend
    is-share: false
    # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
    token-style: uuid
    # 是否输出操作日志
    is-log: false
    # OAuth2.0 配置
    oauth2-server:
        # 是否全局开启授权码模式
        enable-authorization-code: true
        # 是否全局开启 Implicit 模式
        enable-implicit: true
        # 是否全局开启密码模式
        enable-password: true
        # 是否全局开启客户端模式
        enable-client-credentials: true
        # 定义哪些 scope 是高级权限，多个用逗号隔开
        # higher-scope: openid,userid
        # 定义哪些 scope 是低级权限，多个用逗号隔开
        # lower-scope: userinfo

auto-table:
    # 是否开启自动建表功能
    enable: true
    # 是否输出banner
    show-banner: false
    # 是否开启严格继承模式
    strict-extends: true